In [ ]:
print("hello")

In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

# Data Tupe of pandas : Series , DataFrame

### Series : 1 Dimensional Column of data

In [2]:
Car = pd.Series(["Toyota" , "BMW" , "Mercedes"])
Car

0      Toyota
1         BMW
2    Mercedes
dtype: str

In [3]:
Color = pd.Series(["Red" , "Blue" , "Black"])
Color

0      Red
1     Blue
2    Black
dtype: str

# Data Frame : Row and Column

In [6]:
Car_Data = pd.DataFrame({
    "Car_Type" : Car , 
    "Car_Color" : Color
})
Car_Data

   Car_Type Car_Color
0    Toyota       Red
1       BMW      Blue
2  Mercedes     Black

# Practice Exercise

In [9]:
Foods = pd.Series(["Pizza" , "Burger" , "Shawrma" , "Rise"])
Prices = pd.Series([10 , 20 , 5 , 6])
Foods_Menu = pd.DataFrame(
    {
        "Food_Types" : Foods,
        "Price_in_Dollar" : Prices
    }
)
Foods_Menu

  Food_Types  Price_in_Dollar
0      Pizza               10
1     Burger               20
2    Shawrma                5
3       Rise                6

# Import  data

In [29]:
cars = pd.read_csv("../pandas/car-type.csv")
cars

        Car Type  Color  Doors  Price
0   Toyota Camry  White      4  28000
1    Honda Civic  Black      4  25000
2   Ford Mustang    Red      2  42000
3         BMW X5   Blue      4  65000
4  Jeep Wrangler  Green      4  38000

## Export data

In [30]:
cars.to_csv("../pandas/car-type.exported.csv")

# Describe Data

In [31]:
cars.dtypes

Car Type      str
Color         str
Doors       int64
Price       int64
dtype: object

In [32]:
cars.describe()

          Doors         Price
count  5.000000      5.000000
mean   3.600000  39600.000000
std    0.894427  15820.872289
min    2.000000  25000.000000
25%    4.000000  28000.000000
50%    4.000000  38000.000000
75%    4.000000  42000.000000
max    4.000000  65000.000000

In [33]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Car Type  5 non-null      str
 1   Color     5 non-null      str
 2   Doors     5 non-null      int64
 3   Price     5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [34]:
cars.mean(numeric_only=True)

Doors        3.6
Price    39600.0
dtype: float64

In [35]:
cars.sum(numeric_only=True)

Doors        18
Price    198000
dtype: int64

# Viewing and Selecting Data

In [41]:
cars.head()

        Car Type  Color  Doors  Price
0   Toyota Camry  White      4  28000
1    Honda Civic  Black      4  25000
2   Ford Mustang    Red      2  42000
3         BMW X5   Blue      4  65000
4  Jeep Wrangler  Green      4  38000

## Get Data from indexing

In [42]:
cars

        Car Type  Color  Doors  Price
0   Toyota Camry  White      4  28000
1    Honda Civic  Black      4  25000
2   Ford Mustang    Red      2  42000
3         BMW X5   Blue      4  65000
4  Jeep Wrangler  Green      4  38000

In [43]:
cars.loc[1]

Car Type    Honda Civic
Color             Black
Doors                 4
Price             25000
Name: 1, dtype: object

# Filtration

In [44]:
cars

        Car Type  Color  Doors  Price
0   Toyota Camry  White      4  28000
1    Honda Civic  Black      4  25000
2   Ford Mustang    Red      2  42000
3         BMW X5   Blue      4  65000
4  Jeep Wrangler  Green      4  38000

In [45]:
cars[cars["Price"]>30000]

        Car Type  Color  Doors  Price
2   Ford Mustang    Red      2  42000
3         BMW X5   Blue      4  65000
4  Jeep Wrangler  Green      4  38000

In [ ]:
cars[cars["Car Type"] == "BMW X5"]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3257904265.py, line 1)